
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.AssetScalarFieldEnum = {
  id: 'id',
  demiRbasNo: 'demiRbasNo',
  serialNo: 'serialNo',
  categoryId: 'categoryId',
  brandModel: 'brandModel',
  status: 'status',
  locationId: 'locationId',
  assignedUserId: 'assignedUserId',
  purchaseDate: 'purchaseDate',
  purchaseCost: 'purchaseCost',
  salvageValue: 'salvageValue',
  usefulLifeYears: 'usefulLifeYears',
  warrantyEnd: 'warrantyEnd',
  customFields: 'customFields',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AssetCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.LocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parentId: 'parentId'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  permissions: 'permissions',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  title: 'title',
  canLogin: 'canLogin',
  roleId: 'roleId',
  managedLocationIds: 'managedLocationIds'
};

exports.Prisma.AssetHistoryScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  userId: 'userId',
  actionType: 'actionType',
  notes: 'notes',
  documentUrl: 'documentUrl',
  createdAt: 'createdAt'
};

exports.Prisma.TenantSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  actionType: 'actionType',
  module: 'module',
  description: 'description',
  metadata: 'metadata',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.MaintenanceRecordScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  type: 'type',
  provider: 'provider',
  cost: 'cost',
  invoiceNo: 'invoiceNo',
  details: 'details',
  documentUrl: 'documentUrl',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LicenseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  key: 'key',
  seats: 'seats',
  purchaseCost: 'purchaseCost',
  purchaseDate: 'purchaseDate',
  expirationDate: 'expirationDate',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LicenseAssignmentScalarFieldEnum = {
  id: 'id',
  licenseId: 'licenseId',
  userId: 'userId',
  assignedAt: 'assignedAt'
};

exports.Prisma.ConsumableScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  quantity: 'quantity',
  minQuantity: 'minQuantity',
  cost: 'cost',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConsumableHistoryScalarFieldEnum = {
  id: 'id',
  consumableId: 'consumableId',
  actionType: 'actionType',
  quantity: 'quantity',
  userId: 'userId',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.InventoryAuditScalarFieldEnum = {
  id: 'id',
  locationId: 'locationId',
  userId: 'userId',
  status: 'status',
  totalExpected: 'totalExpected',
  totalFound: 'totalFound',
  totalMissing: 'totalMissing',
  totalWrongLoc: 'totalWrongLoc',
  totalUnknown: 'totalUnknown',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryAuditItemScalarFieldEnum = {
  id: 'id',
  auditId: 'auditId',
  assetId: 'assetId',
  scannedCode: 'scannedCode',
  status: 'status',
  scannedAt: 'scannedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  message: 'message',
  type: 'type',
  link: 'link',
  isRead: 'isRead',
  emailSent: 'emailSent',
  createdAt: 'createdAt',
  readAt: 'readAt'
};

exports.Prisma.TicketScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  assetId: 'assetId',
  createdById: 'createdById',
  assignedToId: 'assignedToId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TicketCommentScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  userId: 'userId',
  content: 'content',
  isInternal: 'isInternal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AssetFormScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  userId: 'userId',
  assignedById: 'assignedById',
  type: 'type',
  status: 'status',
  documentContent: 'documentContent',
  signatureData: 'signatureData',
  signedAt: 'signedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Asset: 'Asset',
  AssetCategory: 'AssetCategory',
  Location: 'Location',
  Role: 'Role',
  User: 'User',
  AssetHistory: 'AssetHistory',
  TenantSetting: 'TenantSetting',
  SystemLog: 'SystemLog',
  MaintenanceRecord: 'MaintenanceRecord',
  License: 'License',
  LicenseAssignment: 'LicenseAssignment',
  Consumable: 'Consumable',
  ConsumableHistory: 'ConsumableHistory',
  InventoryAudit: 'InventoryAudit',
  InventoryAuditItem: 'InventoryAuditItem',
  Notification: 'Notification',
  Ticket: 'Ticket',
  TicketComment: 'TicketComment',
  AssetForm: 'AssetForm'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
